#pragma once

// setting to 1 uses a ima wav decoder and encoder that does not use any macros and thus can be debugged
#  define DEBUG 0

#  define AV_HAVE_BIGENDIAN 0
#  define CACHED_BITSTREAM_READER 0
#  define BITSTREAM_READER_LE 1
#  define BITSTREAM_WRITER_LE 1

/**
 * @ingroup lavc_decoding
 * Required number of additionally allocated bytes at the end of the input
 * bitstream for decoding. This is mainly needed because some optimized
 * bitstream readers read 32 or 64 bit at once and could read over the end.<br>
 * Note: If the first 23 bits of the additional bytes are not 0, then damaged
 * MPEG bitstreams could cause overread and segfault.
 */
#  define AV_INPUT_BUFFER_PADDING_SIZE 64


// activate the encoders & decoders by changing 0 to 1
#ifndef CONFIG_ADPCM_4XM_DECODER
#  define CONFIG_ADPCM_4XM_DECODER 0
#endif
#ifndef CONFIG_ADPCM_ADX_DECODER
#  define CONFIG_ADPCM_ADX_DECODER 0
#endif
#ifndef CONFIG_ADPCM_ADX_ENCODER
# define CONFIG_ADPCM_ADX_ENCODER 0
#endif
#ifndef CONFIG_ADPCM_AFC_DECODER
#  define CONFIG_ADPCM_AFC_DECODER 0
#endif
#ifndef CONFIG_ADPCM_AGM_DECODER
#  define CONFIG_ADPCM_AGM_DECODER 0
#endif
#ifndef CONFIG_ADPCM_AICA_DECODER
#  define CONFIG_ADPCM_AICA_DECODER 0
#endif
#ifndef CONFIG_ADPCM_ARGO_DECODER
#  define CONFIG_ADPCM_ARGO_DECODER 0
#endif
#ifndef CONFIG_ADPCM_ARGO_ENCODER
#  define CONFIG_ADPCM_ARGO_ENCODER 0
#endif
#ifndef CONFIG_ADPCM_CT_DECODER
#  define CONFIG_ADPCM_CT_DECODER 0
#endif
#ifndef CONFIG_ADPCM_DTK_DECODER
#  define CONFIG_ADPCM_DTK_DECODER 0
#endif
#ifndef CONFIG_ADPCM_EA_DECODER
#  define CONFIG_ADPCM_EA_DECODER 0
#endif
#ifndef CONFIG_ADPCM_EA_MAXIS_XA_DECODER
#  define CONFIG_ADPCM_EA_MAXIS_XA_DECODER 0
#endif
#ifndef CONFIG_ADPCM_EA_R1_DECODER
#  define CONFIG_ADPCM_EA_R1_DECODER 0
#endif
#ifndef CONFIG_ADPCM_EA_R2_DECODER
#  define CONFIG_ADPCM_EA_R2_DECODER 0
#endif
#ifndef CONFIG_ADPCM_EA_R3_DECODER
#  define CONFIG_ADPCM_EA_R3_DECODER 0
#endif
#ifndef CONFIG_ADPCM_EA_XAS_DECODER
#  define CONFIG_ADPCM_EA_XAS_DECODER 0
#endif
#ifndef CONFIG_ADPCM_G722_DECODER
#  define CONFIG_ADPCM_G722_DECODER 0
#endif
#ifndef CONFIG_ADPCM_G722_ENCODER
#  define CONFIG_ADPCM_G722_ENCODER 0
#endif
#ifndef CONFIG_ADPCM_G726_DECODER
#  define CONFIG_ADPCM_G726_DECODER 0
#endif
#ifndef CONFIG_ADPCM_G726_ENCODER
#  define CONFIG_ADPCM_G726_ENCODER 0
#endif
#ifndef CONFIG_ADPCM_G726LE_DECODER
#  define CONFIG_ADPCM_G726LE_DECODER 0
#endif
#ifndef CONFIG_ADPCM_G726LE_ENCODER
#  define CONFIG_ADPCM_G726LE_ENCODER 0
#endif
#ifndef CONFIG_ADPCM_IMA_ACORN_DECODER
#  define CONFIG_ADPCM_IMA_ACORN_DECODER 0
#endif
#ifndef CONFIG_ADPCM_IMA_AMV_DECODER
#  define CONFIG_ADPCM_IMA_AMV_DECODER 0
#endif
#ifndef CONFIG_ADPCM_IMA_AMV_ENCODER
#  define CONFIG_ADPCM_IMA_AMV_ENCODER 0
#endif
#ifndef CONFIG_ADPCM_IMA_ALP_DECODER
#  define CONFIG_ADPCM_IMA_ALP_DECODER 0
#endif
#ifndef CONFIG_ADPCM_IMA_ALP_ENCODER
#  define CONFIG_ADPCM_IMA_ALP_ENCODER 0
#endif
#ifndef CONFIG_ADPCM_IMA_APC_DECODER
#  define CONFIG_ADPCM_IMA_APC_DECODER 0
#endif
#ifndef CONFIG_ADPCM_IMA_APM_DECODER
#  define CONFIG_ADPCM_IMA_APM_DECODER 0
#endif
#ifndef CONFIG_ADPCM_IMA_APM_ENCODER
#  define CONFIG_ADPCM_IMA_APM_ENCODER 0
#endif
#ifndef CONFIG_ADPCM_IMA_CUNNING_DECODER
#  define CONFIG_ADPCM_IMA_CUNNING_DECODER 0
#endif
#ifndef CONFIG_ADPCM_IMA_DAT4_DECODER
#  define CONFIG_ADPCM_IMA_DAT4_DECODER 0
#endif
#ifndef CONFIG_ADPCM_IMA_DK3_DECODER
#  define CONFIG_ADPCM_IMA_DK3_DECODER 0
#endif
#ifndef CONFIG_ADPCM_IMA_DK4_DECODER
#  define CONFIG_ADPCM_IMA_DK4_DECODER 0
#endif
#ifndef CONFIG_ADPCM_IMA_EA_EACS_DECODER
#  define CONFIG_ADPCM_IMA_EA_EACS_DECODER 0
#endif
#ifndef CONFIG_ADPCM_IMA_EA_SEAD_DECODER
#  define CONFIG_ADPCM_IMA_EA_SEAD_DECODER 0
#endif
#ifndef CONFIG_ADPCM_IMA_ISS_DECODER
#  define CONFIG_ADPCM_IMA_ISS_DECODER 0
#endif
#ifndef CONFIG_ADPCM_IMA_MOFLEX_DECODER
#  define CONFIG_ADPCM_IMA_MOFLEX_DECODER 0
#endif
#ifndef CONFIG_ADPCM_IMA_MTF_DECODER
#  define CONFIG_ADPCM_IMA_MTF_DECODER 0
#endif
#ifndef CONFIG_ADPCM_IMA_OKI_DECODER
#  define CONFIG_ADPCM_IMA_OKI_DECODER 0
#endif
#ifndef CONFIG_ADPCM_IMA_QT_DECODER
#  define CONFIG_ADPCM_IMA_QT_DECODER 0
#endif
#ifndef CONFIG_ADPCM_IMA_QT_ENCODER
#  define CONFIG_ADPCM_IMA_QT_ENCODER 0
#endif
#ifndef CONFIG_ADPCM_IMA_RAD_DECODER
#  define CONFIG_ADPCM_IMA_RAD_DECODER 0
#endif
#ifndef CONFIG_ADPCM_IMA_SSI_DECODER
#  define CONFIG_ADPCM_IMA_SSI_DECODER 0
#endif
#ifndef CONFIG_ADPCM_IMA_SSI_ENCODER
#  define CONFIG_ADPCM_IMA_SSI_ENCODER 0
#endif
#ifndef CONFIG_ADPCM_IMA_SMJPEG_DECODER
#  define CONFIG_ADPCM_IMA_SMJPEG_DECODER 0
#endif
#ifndef CONFIG_ADPCM_IMA_WAV_DECODER
#  define CONFIG_ADPCM_IMA_WAV_DECODER 1
#endif
#ifndef CONFIG_ADPCM_IMA_WAV_ENCODER
#  define CONFIG_ADPCM_IMA_WAV_ENCODER 1
#endif
#ifndef CONFIG_ADPCM_IMA_WS_DECODER
#  define CONFIG_ADPCM_IMA_WS_DECODER 1
#endif
#ifndef CONFIG_ADPCM_IMA_WS_ENCODER
#  define CONFIG_ADPCM_IMA_WS_ENCODER 1
#endif
#ifndef CONFIG_ADPCM_MS_DECODER
#  define CONFIG_ADPCM_MS_DECODER 1
#endif
#ifndef CONFIG_ADPCM_MS_ENCODER
#  define CONFIG_ADPCM_MS_ENCODER 1
#endif
#ifndef CONFIG_ADPCM_MTAF_DECODER
#  define CONFIG_ADPCM_MTAF_DECODER 0
#endif
#ifndef CONFIG_ADPCM_PSX_DECODER
#  define CONFIG_ADPCM_PSX_DECODER 0
#endif
#ifndef CONFIG_ADPCM_SBPRO_2_DECODER
#  define CONFIG_ADPCM_SBPRO_2_DECODER 0
#endif
#ifndef CONFIG_ADPCM_SBPRO_3_DECODER
#  define CONFIG_ADPCM_SBPRO_3_DECODER 0
#endif
#ifndef CONFIG_ADPCM_SBPRO_4_DECODER
#  define CONFIG_ADPCM_SBPRO_4_DECODER 0
#endif
#ifndef CONFIG_ADPCM_SWF_DECODER
#  define CONFIG_ADPCM_SWF_DECODER 0
#endif
#ifndef CONFIG_ADPCM_SWF_ENCODER
#  define CONFIG_ADPCM_SWF_ENCODER 0
#endif
#ifndef CONFIG_ADPCM_THP_DECODER
#  define CONFIG_ADPCM_THP_DECODER 0
#endif
#ifndef CONFIG_ADPCM_THP_LE_DECODER
#  define CONFIG_ADPCM_THP_LE_DECODER 0
#endif
#ifndef CONFIG_ADPCM_VIMA_DECODER
#  define CONFIG_ADPCM_VIMA_DECODER 0
#endif
#ifndef CONFIG_ADPCM_XA_DECODER
#  define CONFIG_ADPCM_XA_DECODER 0
#endif
#ifndef CONFIG_ADPCM_XMD_DECODER
#  define CONFIG_ADPCM_XMD_DECODER 0
#endif
#ifndef CONFIG_ADPCM_YAMAHA_DECODER
#  define CONFIG_ADPCM_YAMAHA_DECODER 0
#endif
#ifndef CONFIG_ADPCM_YAMAHA_ENCODER
#  define CONFIG_ADPCM_YAMAHA_ENCODER 0
#endif
#ifndef CONFIG_ADPCM_ZORK_DECODER
#  define CONFIG_ADPCM_ZORK_DECODER 0
#endif
